# see http://www.martyndavis.com/?p=335 for required hack on Ubuntu Precise
# see http://mjo.tc/atelier/2009/02/arduino-cli.html

ARDUINO_DIR   = /usr/share/arduino
ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = arduino-mk/
AVR_TOOLS_DIR = /usr

BOARD_TAG    = leonardo
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = SPI Ethernet Ethernet/utility DynamixelSerial
include arduino-mk/Arduino.mk
