# see http://www.martyndavis.com/?p=335 for required hack on Ubuntu Precise
# see http://mjo.tc/atelier/2009/02/arduino-cli.html

ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = SPI Ethernet Ethernet/utility DynamixelSerial
include /usr/share/arduino/Arduino.mk
